server:
  port: 8321

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    password: lynn
    username: lynn
    url: jdbc:mysql://127.0.0.1:3306/db_bing?useSSL=false&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
  thymeleaf:
    prefix: classpath:/templates/pages/

###################  MyBatis \u914D\u7F6E  #########################
mybatis:
  type-aliases-package: cn.promptness.bing.pojo
  mapper-locations: classpath:/mapper/*.xml


###################  MyBatis \u5206\u9875\u63D2\u4EF6\u914D\u7F6E  ###################
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


#################  \u65E5\u5FD7\u914D\u7F6E   ################################
logging:
  level.root: info
  level.cn.promptness: info
  path: /logs/bing/
  file: sout.log

apr: true
